### ISSUE TITLE
Allow use of form elements in dialog message

### ISSUE THREAD

**Issue by j-tosi** [JayWood/content-warning-v3#17]
I'm trying to create conditions that the user must accept before being able to get past the content warning dialog box. For this, I'm using form elements (checkboxes). However, after I insert the html in the dialog message text field in Wordpress admin, the checkbox elements are stripped out on the front end. For example:

```html
<form name="form1" method="post" action="">
	<p>
		<label>
			<input type="checkbox" name="disclaimer" value="facts-circumstances" id="disclaimer_0">
			The facts and circumstances of your case may differ from the matters in which results and testimonials have been provided.</label>
		<br>
		<label>
			<input type="checkbox" name="disclaimer" value="results-testimonials" id="disclaimer_1">
			All results of cases handled by the firm are not provided and not all clients have given testimonials.</label>
		<br>
		<label>
			<input type="checkbox" name="disclaimer" value="experience-difference" id="disclaimer_2">
			The results and testimonials provided are not necessarily representative of results obtained by the firm or of the experience of all clients or others with the firm. Every case is different, and each client's case must be evaluated and handled on its own merits.</label>
	</p>
</form>
```

The front-end output looks like this:

```html
<form name="form1" method="post" action="">
<p>
		<label></p>
<p>			The facts and circumstances of your case may differ from the matters in which results and testimonials have been provided.</label><br />
		<br><br />
		<label></p>
<p>			All results of cases handled by the firm are not provided and not all clients have given testimonials.</label><br />
		<br><br />
		<label></p>
<p>			The results and testimonials provided are not necessarily representative of results obtained by the firm or of the experience of all clients or others with the firm. Every case is different, and each client's case must be evaluated and handled on its own merits.</label>
	</p>
</form>
```

**Comment by j-tosi** [comment]
Thanks for this. Sorry for my newbiness, but I'm not sure what to do with the code in the link you provided. Does this overwrite something in the plugin?

**Comment by j-tosi** [comment]
What do I need to do in order for the above form elements to appear in the dialog box? Is it possible?

**Comment by JayWood** [comment]
It is possible, you just have to know how to use filters in WordPress.

[Great info on Hooks and Filters](http://code.tutsplus.com/articles/the-beginners-guide-to-wordpress-actions-and-filters--wp-27373)

Reference my above link over a month ago on the filter to use.
https://gist.github.com/8b4bd5d8e21eff6e5ac1

**Comment by j-tosi** [comment]
Thanks for getting back to me. I'm new to Wordpress and don't know how to use filters. Looks like I have some learning to do. As far as the plugin goes, while some HTML is ok, it's not possible to insert form elements (or JavaScript) via the Wordpress admin options panel, correct? Maybe this is a feature that could be added in the future.

**Comment by JayWood** [comment]
It SHOULD be possible, I've not tried it, which is why I created the filter as a kind of fall-back.  If you take that code in the gist I gave you, and drop it in your themes functions.php file, you should be able to save what you want.

**Comment by j-tosi** [comment]
Ah, I understand now. Wasn't sure how to use that code. Unfortunately with my deadline and other project complications, I ended up doing something more manual on the one page that needs the content warning. But I might try it again in the future. Thanks again.
