### ISSUE TITLE
Popup on all pages

### ISSUE THREAD

**Issue by workshopcollective** [JayWood/content-warning-v3#18]
The content warning popup correctly on restricted category, but once i agree on the popup and navigate inside the post category, I have the popup on each page.
I have that on each browser

I have wordpress 4.0
Content Warning v2 Version 3.6.2

**Comment by workshopcollective** [comment]
an example of a page category with posts: http://s002.host-creation.com/~gerardvachez/category/photos/black-charcoaled-dancer/

**Comment by JayWood** [comment]
Thanks, I'll get to this as soon as possible.

**Comment by workshopcollective** [comment]
Hello,

I checked your code, you only need to allow for Posts and category parents if already approved

**Comment by JayWood** [comment]
Already fixed it actually, will be committing it in a bit.  Anytime you find something and know how to fix it feel free to submit a pull request on the development branch.
