### ISSUE TITLE
Dialog not displayed

### ISSUE THREAD

**Issue by speakdigital** [JayWood/content-warning-v3#22]
Hi. I setup your plugin on http://alphamaleflex.com/ 
It is enabled and the entire site button clicked but no dialog is displayed.

Not really sure where to go next to look for what could be causing that?

Thanks for your help.

**Comment by JayWood** [comment]
I see the dialog, not sure what's happening on your end though, maybe browser cache?

**Comment by JayWood** [comment]
Closing issue as no response in 30+ days.
