### ISSUE TITLE
Dialog box is opening on the wrong page

### ISSUE THREAD

**Issue by Moonflake1978** [JayWood/content-warning-v3#23]
I need the content box on one page of my site and it is popping up on the main page when it is loaded. I set the only page to be the specific page. Am I missing some super simple action?

**Comment by JayWood** [comment]
@Moonflake1978 Make sure `Sitewide`, `Home Page` and `Misc. Pages` are un-checked in the settings.  Tested on 4.1.1, with default settings and un-checking those three boxes, yields the desired result.
