### ISSUE TITLE
background img and css styling not supported

### ISSUE THREAD

**Issue by gulevir** [JayWood/content-warning-v3#24]
When i upload a background image (from setting panel) the path is present in the field but nothing happens. Default background color still here.
Same thing when i try to customize background button in the appropriate field :
#cwv3_exit { background-color: #red; }
#cwv3_enter { background-color: #FFFFFF; }.

so i tried to directly edit the css, and nothing happens too.
i maybe doing something wrong ?

(my skills : good understanding of css and html, but bad in php, javascript)

**Comment by JayWood** [comment]
It sounds like your theme may not be using the `wp_head()` call in the `header.php` file.

**Comment by gulevir** [comment]
thanks for reply. At the end of header.php i see 
<?php wp_head(); ?>
</head>

anything wrong ?
I tried with another themes and same problem.

**Comment by JayWood** [comment]
Thanks for the detailed report.  I'll test this out Saturday, or maybe later today and get back to you.  To confirm, you are on the latest version of the plugin right?

**Comment by gulevir** [comment]
I think so. I just downloaded it from wordpress plug ins 5 days ago

**Comment by JayWood** [comment]
Yea you're definitely on the latest version, I'll see what I can come up with and let you know.  Today if time permits, or tomorrow at the latest.

**Comment by JayWood** [comment]
@gulevir I completely forgot about this sorry.  The styling has changed dramatically in the latest version.  Newer versions use classes instead of IDs.  so `#cwv3_enter{}` becomes `.cwv3_enter{}`
