### ISSUE TITLE
No cookie for Exit button

### ISSUE THREAD

**Issue by meowtoo** [JayWood/content-warning-v3#25]
Hi, is it possible to save no cookie for the Exit button so that people will get asked again next time they visit the site?

**Comment by JayWood** [comment]
If they click exit, the dialog never sets a cookie.  If I remember correctly, you can set your cookie lifetime to 0, which means the `accept` cookie is only set for the life of the session, essentially until the browser is closed.

**Comment by ljmac** [comment]
But that doesn't seem to be the way it works - if no cookie is set, then when they go back, they should be presented with the content warning again. But I found that if the user clicks exit, the content warning is not presented again.
