### ISSUE TITLE
background image not working

### ISSUE THREAD

**Issue by adangvu1972** [JayWood/content-warning-v3#27]
I tried to add a background image in Content-Warning admin, but it still showed the color and opacity. So I added to the custom css section to overwrite the .cwv3.dialog-overlay tag. 

The image now shows up now, however it gets repeated and I want the background image to go full screen, centered and no repeat but it's still getting the tiling of the background image. Not sure what to do. 

Website is  http://www.kikoriwhiskey.com

This is the custom css I added to try to change the background image in the Custom CSS admin section:

.cwv3.dialog-overlay{
background-image: url("http://www.kikoriwhiskey.com/wp-content/uploads/2015/08/MG_9118Kikori.jpg");

  /* Set rules to fill background */
  min-height: 100%;
  min-width: 1024px;
	
  /* Set up proportionate scaling */
  width: 100%;
  height: auto;
	
  /* Set up positioning */
  position: fixed;
  top: 0;
  left: 0;
}

Am I doing something wrong?

**Comment by JayWood** [comment]
Not sure why the css for the background wasn't working in the first place, but here you go, this should fix your code.

https://gist.github.com/91bf9f673c7311090d68

Notice the use of the repeat, attachment, and position parameters for the background property.
[See w3Schools article on background positioning](http://www.w3schools.com/cssref/pr_background-position.asp)

**Comment by JayWood** [comment]
No response in almost a month, so closing.
