### ISSUE TITLE
The popup is disappeared after 1 approval

### ISSUE THREAD

**Issue by sergeyk93** [JayWood/content-warning-v3#29]
Hi,

First of all thank you for the plugin, it's great. I have one issue with it though. It works fine in my site, I use it only for the home page, however, after pressing enter once the popup won't show up again unless i clear my cookies. I thought if I'd enter 0 in the cookie life field it would create a cookie just for the browsing session, however in that case it doesn't create a cookie at all and the pop up just pops after each click. I saw in your video that it's possible that the pop up will show in every time you enter a page, that's what I'd like.
I'm using the latest version: 3.6.4.

Thank you very much!

**Comment by sergeyk93** [comment]
I forgot to mention, I'm using the latest version: 3.6.4.

**Comment by JayWood** [comment]
@sergeyk93 thanks for the reminder, I seen this bug as well, will be fixed in a day or so, sorry for the inconvenience.

**Comment by sergeyk93** [comment]
I'll be waiting for an update, thank you very much for the response and the plugin :)

**Comment by sergeyk93** [comment]
Hi,

I've updated to the newest version, yet the bug still occurs. When I click enter the popup pops again.

**Comment by JayWood** [comment]
@sergeyk93 make sure you cleared your browser cache, as well as your sites cache, if you cache pages.

**Comment by sergeyk93** [comment]
I've tried clearing the cache before I posted this message.
And sure thing, here's a photo:
![untitled](https://cloud.githubusercontent.com/assets/6240807/9704650/3a8f67f0-54b6-11e5-83ef-c7cb360a18fa.png)

**Comment by JayWood** [comment]
@sergeyk93 I'm unable to replicate the issue with the same settings ( aside from the content in the popup of course )  See attached gif.
![csv3_cookie](https://cloud.githubusercontent.com/assets/2303074/9705507/d08f36a8-5494-11e5-8a12-dcbb96c597ef.gif)

**Comment by sergeyk93** [comment]
The enter link should be '#'?
Because the enter link in my is the URL to my site, perhaps that's the problem?

**Comment by JayWood** [comment]
aha! That may be it, will test!

**Comment by sergeyk93** [comment]
Sorry, I've forgot to update!
I've already tested it and it works :)
Thanks for the update!

**Comment by JayWood** [comment]
So you changed the url to # instead of an actual url?  If that's the case, this is still a bug, the cookie should set before the redirect occurs.

**Comment by sergeyk93** [comment]
Yes I did.
It was the full URL including 'http://' and I've changed it all to just '#' and it fixed it.
Happy debugging!

**Comment by JayWood** [comment]
I'm still unable to replicate this, for now I'll close it, if you get the time feel free to post a full screenshot of the broken settings.
