### ISSUE TITLE
Custom css wont work

### ISSUE THREAD

**Issue by kaptajnnic** [JayWood/content-warning-v3#30]
Hey!
Ive tried to customize the box, with the code:
.cwv3_dialog .cwv3_title { background: #F3BB53; }
.cwv3_btns { background: rgba(0,0,0, .0)}
.cwv3_dialog .cwv3_btns .cwv3_enter a {background-color: #738E7A; border-radius: 6px;}
.cwv3_dialog .cwv3_btns .cwv3_exit a {background-color: #738E7A; border-radius: 6px;}
But nothing happens. I am using the newest version of wordpress. 
How do i do this?

**Comment by JayWood** [comment]
Should be fixed in latest release.
