### ISSUE TITLE
Content Warning v3

### ISSUE THREAD

**Issue by eytantes** [JayWood/content-warning-v3#34]
i mark page to display the warning but when i uncheck in the page the checkbox and update the page is still reaming check

**Comment by JayWood** [comment]
Do you mean when you check the box in the 'page' and THEN un-check it, it will still show?  Are you using any sort of page caching?  Could you provide your settings?

**Comment by eytantes** [comment]
hi
yes that what i mean
u can check in that page
http://rcure.co.il/english/

2015-12-03 23:47 GMT+02:00 JayWood <notifications@github.com>:

**Comment by JayWood** [comment]
@eytantes Fixed it, my conditionals were quite strict.

**Comment by eytantes** [comment]
what it mean?
can i download the fixed version?

2015-12-14 16:44 GMT+02:00 JayWood <notifications@github.com>:

**Comment by JayWood** [comment]
@eytantes It will be uploaded to wordpress.org today, you will get an update notification soon
