### ISSUE TITLE
Adding Custom Post Types

### ISSUE THREAD

**Issue by pquinterojr** [JayWood/content-warning-v3#35]
Hi. Our current theme uses a custom post type called "projects". Your plugin works great on standard posts and pages but doesn't see the project post type to protect those posts. I noticed that in your dev documentation area you gave a hook for adding this support. I am new to adding hooks/filters to wordpress. Could you please give me an idea to where i should add this code to get this custom post type protected. Thanks for all for help

**Comment by JayWood** [comment]
When working with themes it's usually advisable to place the code in the themes functions file.  There are other complex ways of doing it, but this would get the job done.

**Comment by pquinterojr** [comment]
An interesting thing happens when i add the code to my themes function file. It removes the CW Security Option check box in the top right corner of all my standard posts/pages and still doesnt include my custom post type i am trying to include. When i remove the code from the function file, all goes back to normal on the standard posts/pages. Any suggestions on how to get this working? Could it be my theme? :)  thanks again for any help

**Comment by JayWood** [comment]
That makes me wonder if I screwed up and forgot to filter the metabox as well.  Let me test and I'll post the code when I'm done.

**Comment by JayWood** [comment]
Sorry for the delay, but I could not replicate the issue, see screenshot below. Make sure your slug for the custom post type is correct when you return it.

![working-cpt](https://cloud.githubusercontent.com/assets/2303074/11784117/af90f93a-a248-11e5-94bd-1fcff22990af.jpg)

**Comment by JayWood** [comment]
Marking resolved, feel free to re-open should you see the need.
