### ISSUE TITLE
Re-Confirm after navigation.

### ISSUE THREAD

**Issue by 95CivicSi** [JayWood/content-warning-v3#36]
Plugin Version 3.6.7
WordPress Version 4.4.2
Using WooCommerce Version 2.5.2
MyStile Theme Version 1.3.11

Current Settings:

Sitewide: Enabled

Home Page: Enabled

Misc Pages: Enabled

Cookie Life: 3

Dialog Title: You Must Be Age 18 or Older to Continue

Dialog Message: <h3>The content of this website is about the use and sale of "Vape" style products.  By continuing to use the site, you agree that you are of legal age in your area, to own such products.<h3>

Exit Text: Exit

Exit Link: http://google.com

Enter Text: Enter

Enter Link: #
 
Toggle Denial Option: Not Checked

Denial Handling Method: Redirect the user. 

Dialog Title: Access Denied

Denial Message: You have been denied access to this content. If you feel this is in error, please contact a site administrator.

Background Image is defined.

Background Opacity: 0.85

Background Color: Black

Custom CSS: in use

Category Restrictions: None selected.

When a visitor accesses the site and is not logged in, they are presented with the correct prompts and redirects work correctly.  After the visitor clicks enter, they are able to view the site until they navigate to another page on the site.  When they navigate to a new page on the site, they are re-prompted.  This happens on all pages, even if the visitor has already clicked the enter text previously on the same page.

**Comment by JayWood** [comment]
@95CivicSi Wow, first of all, thanks for providing a detailed issue, it makes it that much easier to debug.

It sounds like something is up with the site-wide setting. I'll have some time this weekend to debug and get back with you.

**Comment by 95CivicSi** [comment]
I did not mention this directly in my previous post, but users who are logged in are not presented with the age verification at any point.  I felt that this was expected behavior but I feel it is important to know this.

**Comment by JayWood** [comment]
@95CivicSi thank you - I'm hoping to get some time to look into this in the weekend ahead.

**Comment by 95CivicSi** [comment]
The problem is connected to the use of WooCommerce as well as CWV3.  I'm not familiar with how cookies are created using the jQuery Cookie Plugin v1.4.1, but WC appears to be using the same plugin for cart information.

On my test site I was able to get rid of the problem by deactivating WC then reactivating it.  After that, I was unable to recreate the problem without starting from scratch.

My main site still has the issue so I'l leave it for the time being to help figure this out.

**Comment by 95CivicSi** [comment]
So apparently my previous test was a fluke.  I tried the previous method on my main site with no change.  I went back to my test site to see if I missed something and my test site is still acting out.  I'm going to look further into this in the next few days.

**Comment by 95CivicSi** [comment]
I finally got some time to start looking into this again.  The sites that I used to test this with use a subfolder for the WP installation and re-writes the url so the WP folder is not displayed.  For example:

Actual URL
http://www.somewebsite.com/wordpressfolder/index.php

Displayed URL
http://www.somewebsite.com/index.php

This may be causing the problem because because the cookie is set for the url with the wordpress folder included.  So when the page loads, the script checks for a cookie with the re-written URL and doesn't find one.  When it creates the cookie, it then uses the actual URL instead of the current URL.

I am testing this by changing how my site is setup.  I'll update when I'm finished.

**Comment by 95CivicSi** [comment]
So after changing my site settings so that the WP install folder was at the root of the site folder, the plugin works as expected.  My test site is running WooCommerce and nothing appears to break on either side with the CWV3 plugin activated.

I'm going to close this bug and open a new one with a correct bug label.
