### ISSUE TITLE
Background image

### ISSUE THREAD

**Issue by bcsbud** [JayWood/content-warning-v3#37]
Hi! First of all, this plugin is great, my only problem is, that it does not matter what kind of picture I tried to upload, none of them was shown by the plugin via entering the site. All other parts are ok, just the background image is not working for me. Please help to solve this issue.

Thanks in advance!

Br,

cs

**Comment by JayWood** [comment]
@bcsbud off the top of my head I can't think of a reason this would happen - I'll review the code and get back with you.  I thought I squashed all the css related bugs a version or two ago, but I'm not perfect, so rather than assuming I'm right, I'll have a look into the code.

**Comment by bcsbud** [comment]
@JayWood Many thanks, waiting for your answer, have a nice day! :)

**Comment by 95CivicSi** [comment]
bcsbud, you can get around this problem temporarily by adding the following css to your "Custom CSS" section at the bottom of the settings page.

.cwv3.dialog-overlay {
background: url( _put the url for your image here_ ) no-repeat fixed center;
}



You can further adjust how the background looks by changing or adjusting other properties.

Have a look here for information on the css background property rule

http://www.w3schools.com/cssref/css3_pr_background.asp

**Comment by bcsbud** [comment]
Thanks, I will try it and come back with the results.

**Comment by bcsbud** [comment]
@95CivicSi many thanks, it works fine now! Have a nice weekend! :+1:  :)
