### ISSUE TITLE
Content warning plugin

### ISSUE THREAD

**Issue by EQuick78** [JayWood/content-warning-v3#39]
Hi Jay, I installed your plug in and I see potential here but I have a couple pretty serious issues. The Dialog title shows up but not the dialog message. Also, I have uploaded a picture to be used as a background and it is not displaying my image. I checkered the image URL and it is working but not working with your plugin. It just shows my site with barely visible opacity, which is no good for me, as this is an adult based site I need to make sure users do not make it past the content warning page at all or in any form until they agree that they are old enough to enter. Will be looking forward to your reply and thanks in advance.

**Comment by JayWood** [comment]
@EQuick78 The background image issue is apparently rampant in the latest release, check out Issue #37 for a fix.

The rest really sounds like a css conflict issue. If you'd like me to look at the site directly use my contact page here; http://www.plugish.com/contact/ and send me a link to  your site.

**Comment by JayWood** [comment]
No reply in 2 weeks, closing, feel free to re-open.
