### ISSUE TITLE
Problem display on iPhone

### ISSUE THREAD

**Issue by cbardet** [JayWood/content-warning-v3#4]
![photo_2014-08-13_21-38-25](https://cloud.githubusercontent.com/assets/8441791/3911500/d8630904-2321-11e4-9084-73822808190d.jpg)
![photo_2014-08-13_21-41-49](https://cloud.githubusercontent.com/assets/8441791/3911504/e6f3b2f2-2321-11e4-92d1-5d65c2da8e0d.jpg)

Hi,
On iPhone, the button are not accessible.
You can't click on Enter or Quit...

**Comment by JayWood** [comment]
Since the new rewrite of the popup, if someone can test this that would be great!
