### ISSUE TITLE
CSS not working v3.6.9

### ISSUE THREAD

**Issue by aerynwalker** [JayWood/content-warning-v3#46]
Seems to be same as old css errors. No custom css is working at all on v3.6.9

**Comment by JayWood** [comment]
I realize this is a few months too late, but I've confirmed that the custom CSS does indeed work on the latest version. Closing this for now.

![c0e54957e736be3df941b75f8ae1c854](https://cloud.githubusercontent.com/assets/2303074/18993211/18e2ced6-86f0-11e6-97fa-f5afe336c6a7.png)
