### ISSUE TITLE
Category restrictions not showing up

### ISSUE THREAD

**Issue by Silkheart** [JayWood/content-warning-v3#47]
Hi

I have installed and activated the plug in. Went to set it up for certain categories only, but alas there are no categories to choose from.

I have made sure i have categories in pages and products to see if that could be the issue, but i'm now at a loss and don't understand what else I could try.

Novice trying hard in this computer age!

Any assistance would be greatly appreciated. Thank you

![content warning v3 - issue](https://cloud.githubusercontent.com/assets/19797460/15855231/407894c0-2ca6-11e6-8753-eeb1a62f8be7.jpg)

**Comment by JayWood** [comment]
Not sure why categories wouldn't be showing up.  What WordPress version are you using?

**Comment by Silkheart** [comment]
Hi

I'm running WordPress 4.5.2 with Storefront theme.

I'm at a loss, can normally work most problems out, but this is out of my
league.

Kind Regards

Ang

**Comment by JayWood** [comment]
@Silkheart I've confirmed this is working as expected with 4.5.3, see attached image.
![0e421a306f1b7c432be076028a91538b](https://cloud.githubusercontent.com/assets/2303074/16498262/fb457aaa-3ec8-11e6-8504-627874deddf2.png)

**Comment by JayWood** [comment]
Closing, feel free to re open, no reply in 14+ days.
