### ISSUE TITLE
Feature request: make option accessible for custom post types trough menu

### ISSUE THREAD

**Issue by kloneets** [JayWood/content-warning-v3#48]
If I use custom post types than option doesn't appear in admin view, so I can not put restriction for one custom post.

**Comment by JayWood** [comment]
There's a filter for that. https://github.com/JayWood/content-warning-v3/wiki/Dev-Documentation#support-multiple-post-types

**Comment by kloneets** [comment]
Thanks...

**Comment by kloneets** [comment]
One more thing, you forgot `return` in multiple posts documentation https://github.com/JayWood/content-warning-v3/wiki/Dev-Documentation#support-multiple-post-types `add_my_post_types` function.

**Comment by JayWood** [comment]
Fixed, thanks for that :+1:
