### ISSUE TITLE
Category restrictions trows error notices (jop_checked)

### ISSUE THREAD

**Issue by kloneets** [JayWood/content-warning-v3#49]
JW_SIMPLE_OPTIONS function `jop_checked` throws error on unchecked categories. Error notice:
```Notice: Array to string conversion in ../wp-includes/general-template.php on line 3550```

You need to stringify $haystack, if match is not met. My quick solution
```PHP
function jop_checked( $haystack, $cur, $show = FALSE ) {
		if ( is_array( $haystack ) && in_array( $cur, $haystack ) ) {
			$cur = $haystack = 1;
		}
		if(is_array($haystack)) { //if $haystack is still an array, take first value
			$haystack = array_shift($haystack);
		}
		return checked( $haystack, $cur, $show );
	}
```

**Comment by JayWood** [comment]
@kloneets yea thanks, simple options is horribly outdated.  It's on my radar.  I plan on moving all settings to the WordPress settings API sometime in the near future.

**Comment by JayWood** [comment]
Related #45 - Tracking there
