### ISSUE TITLE
Set cookies "0" but it still remember the cookiers

### ISSUE THREAD

**Issue by ngoctam1011** [JayWood/content-warning-v3#52]
Hello,
I would like to use the confirm message appears every user surfing a category, so I set the cookies "0" value but the plugin does not work.
It still remembers the cookies.

**Comment by JayWood** [comment]
I'll be looking into this, thanks for the report.

**Comment by JayWood** [comment]
@ngoctam1011 I've just updated the QA section of the wiki - https://github.com/JayWood/content-warning-v3/wiki/F.A.Qs#i-set-the-cookie-time-to-0-but-i-dont-see-the-dialog-when-i-change-the-page

Long story short, browsers will set the cookie life to `session` which means your users will hold onto the cookie until they close their browser window.

I've opened a new enhancement ticket at #58 to hopefully help with what I believe you're looking for.
