### ISSUE TITLE
JS file missing in HTML header?

### ISSUE THREAD

**Issue by derFalk** [JayWood/content-warning-v3#53]
Hi Jerry,

I am having trouble to get your plugin working.
I have set it to show up on the home page. And when I check the source code, I can see the custom CSS and also everything in . So I believe it is not loading the JS file.

I have also checked my theme, which is using wp_head() and wp_footer().

Maybe you can think of what's going wrong?

**Comment by derFalk** [comment]
Okay, I just noted that this is the case when you are logged on.
As soon as you log of, the message appears.

Should've thought of that... :grin:

**Comment by JayWood** [comment]
Yep, didn't want to provide the dialog to logged in users, especially admins.
