### ISSUE TITLE
Pluging is not displaying on Portfolios.

### ISSUE THREAD

**Issue by radrat** [JayWood/content-warning-v3#54]
Hi. I’ve installed the plugin on my website (WP theme with customised settings). Although It works on pages and posts it doesn't on portfolios. There is any workaround for that?

**Comment by JayWood** [comment]
Portfolios must be a post type, give this a try - https://github.com/JayWood/content-warning-v3/wiki/Dev-Documentation#support-multiple-post-types

**Comment by JayWood** [comment]
Closing, assuming fixed due to no reply in a decent amount of time.
