### ISSUE TITLE
Opacity can't be modified.

### ISSUE THREAD

**Issue by alarcia** [JayWood/content-warning-v3#55]
Hello, and thanks for your awesome plugin.
Default opacity (0.85) seemed so dark, felt like 1. So I went and tried to type 0.60 and save. 
But a dialog prompted and said that what I wrote is not valid, and that the closest values to 0.60 are 0.85 and -0.15. Even though the tooltip says a float value from 0 to 1.
Anyway I chose -0.15 and the opacity was exactly the same as 0.85.
So there's the problem. Thanks for your time!

**Comment by JayWood** [comment]
@alarcia thanks for the report, I'm working on moving from the simple options framework I built a long time ago to a different system, probably the settings API that comes with WordPress.

See #45 - this will obviously fix this bug, it just takes time. I have some life stuff I need to handle before I jump back into the saddle, so keep a watch on that ticket for updates.
