### ISSUE TITLE
Misc. Pages

### ISSUE THREAD

**Issue by asuvalovs** [JayWood/content-warning-v3#59]
Misc. Pages not working since update.

I can't select more than one category what I wold like restrict. 

How can I download previous version what was before? 

Thank you

**Comment by JayWood** [comment]
Ouch, sorry about that, I'll give that a test and see what's up. - You can always download version by checking the releases tab here. Here is a link for the previous release https://github.com/JayWood/content-warning-v3/releases/tag/3.6.9

**Comment by asuvalovs** [comment]
I had error if I try install previous versions. I'm try last 5 options. 

Warning: require_once(/home/gozebrac/public_html/wp-content/plugins/content-warning-v3-3.6.1/lib/jw_simple_options/simple_options.php): failed to open stream: No such file or directory in /home/gozebrac/public_html/wp-content/plugins/content-warning-v3-3.6.1/content-warning-v3.php on line 16

**Comment by JayWood** [comment]
https://downloads.wordpress.org/plugin/content-warning-v2.3.6.9.zip

**Comment by JayWood** [comment]
forgot about the submodule

**Comment by asuvalovs** [comment]
Thx Jay!
You do great job!! 
Respect to you :)

**Comment by JayWood** [comment]
After some pretty in-depth testing, I was unable to recreate the misc. pages issue on the current 3.7.1 release. Assuming fixed, so closing.
